spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_system
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    enabled: true
server:
  port: 8080
